# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
