# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200221_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='products',
            field=models.ManyToManyField(related_name='_review_products_+', to='reviews.Review'),
        ),
    ]
